### ISSUE TITLE
PowerPlay table

### ISSUE THREAD

**Issue by Perfect-Web** [OhGodACompany/OhGodATool#5]
`Unable to read entire PowerPlay table. (read 812, size was 12338)`

any idea what could cause this ?

**Comment by OhGodAPet** [comment]
A kernel older than Jesus. You may be using Ubuntu.

**Comment by gboddin** [comment]
Confirmed 

https://gist.github.com/gboddin/bbf10dc51cd468fba93e8f4e17c51859#amd--polaris-tested-possibly-all-other-cards-supported-by-amdgpu-

It works starting from 4.11.
